image: node:18-alpine

stages:
  - build
  - test
  - publish
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      variables:
        IMAGE_TAG: "dev"
        REMOTE_URL: $REMOTE_URL_DEVELOP
        API_URL: $API_URL_DEVELOP
        DIRECTUS_URL: $DIRECTUS_URL_DEVELOP
        DIRECTUS_TOKEN: $DIRECTUS_TOKEN_DEVELOP
        AUTH_PROVIDER: $AUTH_PROVIDER_DEVELOP
        B2C_TENANT: $B2C_TENANT_DEVELOP
        B2C_CLIENT_ID: $B2C_CLIENT_ID_DEVELOP
        B2C_USER_FLOW: $B2C_USER_FLOW_DEVELOP
        B2C_REDIRECT_URI: $B2C_REDIRECT_URI_DEVELOP
    - if: '$CI_COMMIT_TAG == "gaza-dev"'
      variables:
        IMAGE_TAG: "gaza-dev"
        REMOTE_URL: $REMOTE_URL_GAZA_DEV
        API_URL: $API_URL_GAZA_DEV
        DIRECTUS_URL: $DIRECTUS_URL_GAZA_DEV
        DIRECTUS_TOKEN: $DIRECTUS_TOKEN_GAZA_DEV
        AUTH_PROVIDER: $AUTH_PROVIDER_GAZA_DEV
        B2C_TENANT: $B2C_TENANT_GAZA_DEV
        B2C_CLIENT_ID: $B2C_CLIENT_ID_GAZA_DEV
        B2C_USER_FLOW: $B2C_USER_FLOW_GAZA_DEV
        B2C_REDIRECT_URI: $B2C_REDIRECT_URI_GAZA_DEV
    - if: '$CI_COMMIT_TAG == "urc"'
      variables:
        IMAGE_TAG: "urc"
        REMOTE_URL: $REMOTE_URL_URC
        API_URL: $API_URL_URC
        DIRECTUS_URL: $DIRECTUS_URL_URC
        DIRECTUS_TOKEN: $DIRECTUS_TOKEN_URC
        AUTH_PROVIDER: $AUTH_PROVIDER_URC
        B2C_TENANT: $B2C_TENANT_URC
        B2C_CLIENT_ID: $B2C_CLIENT_ID_URC
        B2C_USER_FLOW: $B2C_USER_FLOW_URC
        B2C_REDIRECT_URI: $B2C_REDIRECT_URI_URC
    - when: always

build-client:
  stage: build
  before_script:
    - apk update
    - apk add yarn
  script:
    - echo "Building CCD client"
    - cd client
    - yarn
    - echo VITE_API_URL=$API_URL > .env
    - echo VITE_DIRECTUS_URL=$DIRECTUS_URL >> .env
    - echo VITE_DIRECTUS_TOKEN=$DIRECTUS_TOKEN >> .env
    - echo VITE_AUTH_PROVIDER=$AUTH_PROVIDER >> .env
    - echo VITE_B2C_TENANT=$B2C_TENANT >> .env
    - echo VITE_B2C_CLIENT_ID=$B2C_CLIENT_ID >> .env
    - echo VITE_B2C_USER_FLOW=$B2C_USER_FLOW >> .env
    - echo VITE_B2C_REDIRECT_URI=$B2C_REDIRECT_URI >> .env
    - yarn build
    - mv dist ../client-build
    - echo "Build successful"
  artifacts:
    expire_in: 1 hour
    name: client-build
    paths:
      - client-build

build-server:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
  before_script:
    - apk update
    - apk add nodejs npm
  script:
    - echo "Building CCD server"
    - cd server
    - npm install
    - npm run build
    - mv Ccd.Server/build ../server-build
    - echo "Build successful"
  artifacts:
    expire_in: 1 hour
    name: server-build
    paths:
      - server-build

test-server:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0-alpine
  services:
    - name: postgres
      alias: ccd-server
  variables:
    POSTGRES_DB: ccd-server
    POSTGRES_USER: ccd-server
    POSTGRES_PASSWORD: test123
  before_script:
    - apk update
    - apk add nodejs npm
  script:
    - echo "Running CCD server tests"
    - cd server
    - rm Ccd.Tests/appsettings.json
    - rm Ccd.Server/appsettings.json
    - cp Ccd.Tests/appsettings.ci.json Ccd.Tests/appsettings.json
    - cp Ccd.Tests/appsettings.ci.json Ccd.Server/appsettings.json
    - npm run test
    - echo "Tests successful"

publish-client:
  stage: publish
  only:
    - develop
    - poc
    - tags
  services:
    - docker:26.1.4-dind
  before_script:
    - apk update
    - apk add docker
  script:
    - echo "Publishing client (ID $CI_PIPELINE_ID)"
    - cp client/deployment/Dockerfile client-build
    - cp client/deployment/nginx.conf client-build
    - cd client-build
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --load -t $CI_REGISTRY/init/ccd-data-portal/image:client-$IMAGE_TAG .
    - docker push $CI_REGISTRY/init/ccd-data-portal/image:client-$IMAGE_TAG
    - echo "Publishing complete"

publish-server:
  stage: publish
  only:
    - develop
    - poc
    - tags
  services:
    - docker:26.1.4-dind
  before_script:
    - apk update
    - apk add docker
  script:
    - echo "Publishing client (ID $CI_PIPELINE_ID)"
    - cp server/deployment/Dockerfile server-build
    - cd server-build
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --load -t $CI_REGISTRY/init/ccd-data-portal/image:server-$IMAGE_TAG .
    - docker push $CI_REGISTRY/init/ccd-data-portal/image:server-$IMAGE_TAG
    - echo "Publishing complete"

deploy:
  stage: deploy
  only:
    - develop
    - poc
    - tags
  except:
    variables:
      - $CI_COMMIT_TAG == "save-the-children"
  before_script:
    - apk update
    - apk add openssh rsync bash
    - mkdir /root/.ssh
    - touch /root/.ssh/id_rsa
    - echo -e $SSH_KEY | awk '{gsub("\\\\n","\n")};1' >> /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
  script:
    - echo "Deploying app (ID $CI_PIPELINE_ID)"
    - ssh -o StrictHostKeyChecking=no ubuntu@$REMOTE_URL /home/ubuntu/run-services.sh
    - echo "Deployment complete"
